services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - './config/grafana/grafana.ini:/etc/grafana/grafana.ini'
      - './config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml'
  influxdb:
    image: influxdb:2.7
    ports:
      - 8086:8086
    volumes:
      - influx-vol:/var/lib/influxdb2
    environment:
      - TZ=America/Buenos_Aires
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=supersecret
      - DOCKER_INFLUXDB_INIT_ORG=unahur
      - DOCKER_INFLUXDB_INIT_BUCKET=ope
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
  mqtt:
    image: eclipse-mosquitto:2
    environment:
      - TZ=America/Buenos_Aires
    ports:
      - "8883:1883"
      - "9001:9001"
volumes:
  influx-vol:
